// --============================================--
// --== Copyright (c) 2026 Marc Schraffenberger.
// --==
// --== SPDX-License-Identifier: MIT
// --==
// --== Code generated by literate; DO NOT EDIT.
// --============================================--
package main

import (
	"flag"
	"log/slog"
	"os"
)

func main() {
	//--=====================================================================--
	//--== ARGUMENT PARSING
	//--=====================================================================--

	var output string
	var verbose bool

	flag.StringVar(&output, "output", "", "output path for generated code")
	flag.BoolVar(&verbose, "verbose", false, "verbose logging")
	flag.Parse()

	inputs := flag.Args()

	//--=====================================================================--
	//--== SETUP LOGGING
	//--=====================================================================--

	level := slog.LevelInfo
	if verbose {
		level = slog.LevelDebug
	}

	handler := slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{
		Level: level,
	})

	slog.SetDefault(slog.New(handler))

	//--=====================================================================--
	//--== GENERATE SOURCE CODE FILES
	//--=====================================================================--

	if err := GenerateCode(inputs, output); err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
}
