// --============================================--
// --== Copyright (c) 2026 Marc Schraffenberger.
// --==
// --== SPDX-License-Identifier: MIT
// --==
// --== Code generated by literate; DO NOT EDIT.
// --============================================--
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"iter"
	"log/slog"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/text"
)

func ParseMarkdownFile(filename string) iter.Seq2[*CodeBlock, error] {
	return func(yield func(*CodeBlock, error) bool) {
		slog.Debug("parsing markdown file", slog.String("filename", filename))

		//--=====================================================================--
		//--== PARSE SOURCE FILE DOCUMENT
		//--=====================================================================--

		parser := goldmark.DefaultParser()

		content, err := ioutil.ReadFile(filename)
		if err != nil {
			yield(nil, fmt.Errorf("failed to read file '%s': %w", filename, err))
			return
		}

		reader := text.NewReader(content)
		doc := parser.Parse(reader)

		//--=====================================================================--
		//--== EXTRACT CODE BLOCKS
		//--=====================================================================--

		err = ast.Walk(doc, func(node ast.Node, entering bool) (ast.WalkStatus, error) {
			if !entering {
				return ast.WalkContinue, nil
			}

			if codeBlockNode, ok := node.(*ast.FencedCodeBlock); ok {
				var codeBlock CodeBlock

				//--=====================================================================--
				//--== PARSE CODE BLOCK ATTRIBUTES
				//--=====================================================================--

				info := string(codeBlockNode.Info.Value(content))
				codeBlock.Attributes.Parse(info)

				if codeBlock.Attributes.Name == "" {
					return ast.WalkContinue, nil
				}

				//--=====================================================================--
				//--== EXTRACT CODE BLOCK BODY
				//--=====================================================================--

				var codeBody bytes.Buffer

				lines := codeBlockNode.Lines()

				for i := 0; i < lines.Len(); i++ {
					line := lines.At(i)
					codeBody.Write(line.Value(content))
				}

				codeBlock.Body = codeBody.String()

				//--=====================================================================--
				//--== RETURN NEXT CODE BLOCK
				//--=====================================================================--

				slog.Debug("extracted code block", slog.String("name", codeBlock.Attributes.Name))

				if !yield(&codeBlock, nil) {
					return ast.WalkStop, nil
				}
			}

			return ast.WalkContinue, nil
		})
		if err != nil {
			yield(nil, fmt.Errorf("failed to parse file '%s': %w", filename, err))
			return
		}
	}
}
