// --============================================--
// --== Copyright (c) 2026 Marc Schraffenberger.
// --==
// --== SPDX-License-Identifier: MIT
// --==
// --== Code generated by literate; DO NOT EDIT.
// --============================================--
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

//--=====================================================================--
//--== PROCESSOR
//--=====================================================================--

type Processor struct {
	OutputPath string
}

func NewProcessor(output string) *Processor {
	return &Processor{
		OutputPath: output,
	}
}

func (p Processor) GenerateCodeFiles(blocks *CodeBlockStorage) error {
	processor := NewCodeBlockProcessor(blocks)

	for _, block := range blocks.Files {
		path := filepath.Join(p.OutputPath, block.Attributes.Filename)

		code, err := processor.ProcessCodeBlock(block.Attributes.Name)
		if err != nil {
			return err
		}

		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			return fmt.Errorf("failed to create directory for '%s': %w", path, err)
		}

		if err := ioutil.WriteFile(path, []byte(code), 0644); err != nil {
			return fmt.Errorf("failed to write to file '%s': %w", path, err)
		}

		slog.Debug("saved code file", slog.String("filename", block.Attributes.Filename))
	}

	return nil
}

//--=====================================================================--
//--== CODE BLOCK PROCESSOR
//--=====================================================================--

type CodeBlockProcessor struct {
	Funcs   template.FuncMap
	Storage *CodeBlockStorage
	State   map[string]bool
}

func NewCodeBlockProcessor(storage *CodeBlockStorage) *CodeBlockProcessor {
	processor := &CodeBlockProcessor{
		Storage: storage,
		State:   make(map[string]bool),
	}

	processor.Funcs = template.FuncMap{
		"include": processor.ProcessCodeBlock,
	}

	return processor
}

func (p *CodeBlockProcessor) ProcessCodeBlock(name string) (string, error) {
	if p.State[name] {
		return "", fmt.Errorf("recursive block inclusion: '%s'", name)
	}

	p.State[name] = true
	defer func() { p.State[name] = false }()

	block, ok := p.Storage.Blocks[name]
	if !ok {
		return "", fmt.Errorf("code block '%s' not found", name)
	}

	tmpl, err := template.New(name).Funcs(p.Funcs).Parse(block.Body)
	if err != nil {
		return "", fmt.Errorf("failed to parse code block '%s': %w", name, err)
	}

	var code bytes.Buffer

	if err := tmpl.Execute(&code, nil); err != nil {
		return "", fmt.Errorf("failed to generate code block '%s': %w", name, err)
	}

	return strings.TrimSpace(code.String()), nil
}
